# Calendar properties

This tutorial offers a walk through of ExchangeCalendar properties (for methods see the [calendar methods](./calendar_methods.ipynb) tutorial).

NB properties that _define_ a calendar (`open_times`, `special_closes_adhoc` etc) are not covered by this tutorial (see the [How can I create a new calendar](https://github.com/gerrymanoim/exchange_calendars/tree/master#how-can-i-create-a-new-calendar) section of the [README](https://github.com/gerrymanoim/exchange_calendars/tree/master)).

In [2]:
# set up
import exchange_calendars as xcals
import pandas as pd

hkg = xcals.get_calendar("XHKG", side="left")  # Hong Kong Stock Exchange
nys = xcals.get_calendar("XNYS", side="left")  # New York Stock Exchange

### Calendar construction

The **`bound_*`** properties return the earliest/latest date from/to which a calendar class can be constructed, or None if there is no limit:

In [3]:
hkg.bound_start, hkg.bound_end

(Timestamp('1960-01-01 00:00:00+0000', tz='UTC'),
 Timestamp('2049-12-31 00:00:00+0000', tz='UTC'))

In [4]:
nys.bound_start == nys.bound_end == None

True

**`default_start`**/**`default_end`** return the dates from/to which a calendar will be created if the `start`/`end` parameters are not passed to the constructor (unless limited by the bounds, the defaults are '20 years ago' / '1 year from now'):

In [5]:
nys.default_start, nys.default_end

(Timestamp('2001-10-22 00:00:00+0000', tz='UTC'),
 Timestamp('2022-10-22 00:00:00+0000', tz='UTC'))

**`default_side`** is a class method that returns the calendar's default side in the event `side` is not otherwise passed to the constructor. By default 24-hour calendars are side "right" and all others side "both".

In [6]:
open24 = xcals.get_calendar("24/7")
open24.default_side(), nys.default_side()

('right', 'both')

NB the actual calendar side is returned by the **`side`** property.

In [7]:
nys.default_side(), nys.side

('both', 'left')

**`valid_sides`** is a class method that returns all side values that can be passed to the constructor's `side` parameter:

In [8]:
nys.valid_sides()

['both', 'left', 'right', 'neither']

In [9]:
open24.valid_sides()

['left', 'right']

See the [minutes](./minutes.ipynb) tutorial for an explanation of how a calendar's side determines which minutes are treated as trading minutes.

### General Calendar Properties

In [10]:
nys.name

'XNYS'

In [11]:
nys.tz  # timezone

<DstTzInfo 'America/New_York' LMT-1 day, 19:04:00 STD>

In [12]:
nys.side

'left'

**`day`** returns a `CustomBusinessDay` for the calendar:

In [13]:
# for reference
nys.sessions_in_range("2020-12-29", "2021-01-06")

DatetimeIndex(['2020-12-29 00:00:00+00:00', '2020-12-30 00:00:00+00:00',
               '2020-12-31 00:00:00+00:00', '2021-01-04 00:00:00+00:00',
               '2021-01-05 00:00:00+00:00', '2021-01-06 00:00:00+00:00'],
              dtype='datetime64[ns, UTC]', freq='C')

In [14]:
pd.Timestamp("2020-12-31") + (nys.day * 2)

Timestamp('2021-01-05 00:00:00')

**`has_break`** queries if _any_ calendar session has a break

In [15]:
nys.has_break

False

### Sessions and Minutes

**NOTE:** This section does little more than catalogue the calendar properties concerned with sessions or minutes. See the [sessions](./sessions.ipynb) and [minutes](./minutes.ipynb) tutorials for notes on 'working with sessions/minutes'.

#### All of them

In [16]:
nys.sessions  # DatetimeIndex representing all calendar sessions

DatetimeIndex(['2001-10-22 00:00:00+00:00', '2001-10-23 00:00:00+00:00',
               '2001-10-24 00:00:00+00:00', '2001-10-25 00:00:00+00:00',
               '2001-10-26 00:00:00+00:00', '2001-10-29 00:00:00+00:00',
               '2001-10-30 00:00:00+00:00', '2001-10-31 00:00:00+00:00',
               '2001-11-01 00:00:00+00:00', '2001-11-02 00:00:00+00:00',
               ...
               '2022-10-10 00:00:00+00:00', '2022-10-11 00:00:00+00:00',
               '2022-10-12 00:00:00+00:00', '2022-10-13 00:00:00+00:00',
               '2022-10-14 00:00:00+00:00', '2022-10-17 00:00:00+00:00',
               '2022-10-18 00:00:00+00:00', '2022-10-19 00:00:00+00:00',
               '2022-10-20 00:00:00+00:00', '2022-10-21 00:00:00+00:00'],
              dtype='datetime64[ns, UTC]', length=5289, freq='C')

In [17]:
nys.minutes  # DatetimeIndex representing every calendar trading minute

DatetimeIndex(['2001-10-22 13:30:00+00:00', '2001-10-22 13:31:00+00:00',
               '2001-10-22 13:32:00+00:00', '2001-10-22 13:33:00+00:00',
               '2001-10-22 13:34:00+00:00', '2001-10-22 13:35:00+00:00',
               '2001-10-22 13:36:00+00:00', '2001-10-22 13:37:00+00:00',
               '2001-10-22 13:38:00+00:00', '2001-10-22 13:39:00+00:00',
               ...
               '2022-10-21 19:50:00+00:00', '2022-10-21 19:51:00+00:00',
               '2022-10-21 19:52:00+00:00', '2022-10-21 19:53:00+00:00',
               '2022-10-21 19:54:00+00:00', '2022-10-21 19:55:00+00:00',
               '2022-10-21 19:56:00+00:00', '2022-10-21 19:57:00+00:00',
               '2022-10-21 19:58:00+00:00', '2022-10-21 19:59:00+00:00'],
              dtype='datetime64[ns, UTC]', length=2054430, freq=None)

#### Calendar Bounds

In [18]:
nys.first_session, nys.last_session

(Timestamp('2001-10-22 00:00:00+0000', tz='UTC', freq='C'),
 Timestamp('2022-10-21 00:00:00+0000', tz='UTC', freq='C'))

In [19]:
nys.first_minute, nys.last_minute

(Timestamp('2001-10-22 13:30:00+0000', tz='UTC'),
 Timestamp('2022-10-21 19:59:00+0000', tz='UTC'))

In [20]:
nys.first_session_open, nys.last_session_close

(Timestamp('2001-10-22 13:30:00'), Timestamp('2022-10-21 20:00:00'))

#### Schedule (open, close and break times)

In [21]:
hkg.schedule

market_open         break_start  \
2001-10-22 00:00:00+00:00 2001-10-22 02:00:00 2001-10-22 04:00:00   
2001-10-23 00:00:00+00:00 2001-10-23 02:00:00 2001-10-23 04:00:00   
2001-10-24 00:00:00+00:00 2001-10-24 02:00:00 2001-10-24 04:00:00   
2001-10-26 00:00:00+00:00 2001-10-26 02:00:00 2001-10-26 04:00:00   
2001-10-29 00:00:00+00:00 2001-10-29 02:00:00 2001-10-29 04:00:00   
...                                       ...                 ...   
2022-10-17 00:00:00+00:00 2022-10-17 01:30:00 2022-10-17 04:00:00   
2022-10-18 00:00:00+00:00 2022-10-18 01:30:00 2022-10-18 04:00:00   
2022-10-19 00:00:00+00:00 2022-10-19 01:30:00 2022-10-19 04:00:00   
2022-10-20 00:00:00+00:00 2022-10-20 01:30:00 2022-10-20 04:00:00   
2022-10-21 00:00:00+00:00 2022-10-21 01:30:00 2022-10-21 04:00:00   

                                    break_end        market_close  
2001-10-22 00:00:00+00:00 2001-10-22 05:00:00 2001-10-22 08:00:00  
2001-10-23 00:00:00+00:00 2001-10-23 05:00:00 2001-10-23 08:00:00  
2001-10-24 00:00:00+00:00 2001-10-24 05:00:00 2001-10-24 08:00:00  
2001-10-26 00:00:00+00:00 2001-10-26 05:00:00 2001-10-26 08:00:00  
2001-10-29 00:00:00+00:00 2001-10-29 05:00:00 2001-10-29 08:00:00  
...                                       ...                 ...  
2022-10-17 00:00:00+00:00 2022-10-17 05:00:00 2022-10-17 08:00:00  
2022-10-18 00:00:00+00:00 2022-10-18 05:00:00 2022-10-18 08:00:00  
2022-10-19 00:00:00+00:00 2022-10-19 05:00:00 2022-10-19 08:00:00  
2022-10-20 00:00:00+00:00 2022-10-20 05:00:00 2022-10-20 08:00:00  
2022-10-21 00:00:00+00:00 2022-10-21 05:00:00 2022-10-21 08:00:00  

[5184 rows x 4 columns]

The schedule is a pandas DataFrame. It shows the days the exchange is open and describes the bounds when the exchange is open for regular trading on each of those days.

The index represents the calendar's sessions as a pandas DatetimeIndex with timezone as UTC. For each session, the columns offer the open, close and, if applicable, break-start and break-end time. **The times are defined in UTC terms although the actual columns' DatetimeIndex are tz-naive**.

**NB It's proposed that from version 4.0 the timezone of the columns' DatetimeIndex will be set to "UTC" whilst the index will become tz-naive.** Have your say [here](https://github.com/gerrymanoim/exchange_calendars/issues/42).

The break_start/break_end columns take pd.NaT in the event that a session does not have a break.

In [22]:
hkg.schedule.loc["2020-12-23":"2020-12-28"]

market_open         break_start  \
2020-12-23 00:00:00+00:00 2020-12-23 01:30:00 2020-12-23 04:00:00   
2020-12-24 00:00:00+00:00 2020-12-24 01:30:00                 NaT   
2020-12-28 00:00:00+00:00 2020-12-28 01:30:00 2020-12-28 04:00:00   

                                    break_end        market_close  
2020-12-23 00:00:00+00:00 2020-12-23 05:00:00 2020-12-23 08:00:00  
2020-12-24 00:00:00+00:00                 NaT 2020-12-24 04:00:00  
2020-12-28 00:00:00+00:00 2020-12-28 05:00:00 2020-12-28 08:00:00

The properties **`opens`**, **`closes`**, **`break_starts`** and **`break_ends`** return the corresponding column of the schedule as a pd.Series.

In [23]:
hkg.opens

2001-10-22 00:00:00+00:00   2001-10-22 02:00:00
2001-10-23 00:00:00+00:00   2001-10-23 02:00:00
2001-10-24 00:00:00+00:00   2001-10-24 02:00:00
2001-10-26 00:00:00+00:00   2001-10-26 02:00:00
2001-10-29 00:00:00+00:00   2001-10-29 02:00:00
                                    ...        
2022-10-17 00:00:00+00:00   2022-10-17 01:30:00
2022-10-18 00:00:00+00:00   2022-10-18 01:30:00
2022-10-19 00:00:00+00:00   2022-10-19 01:30:00
2022-10-20 00:00:00+00:00   2022-10-20 01:30:00
2022-10-21 00:00:00+00:00   2022-10-21 01:30:00
Freq: C, Name: market_open, Length: 5184, dtype: datetime64[ns]

As for the schedule, **although these times are defined in terms of UTC, the properties are tz-naive** (again, it's anticipated that from version 4.0 the timezone of these properties will be set to "UTC", see [#42](https://github.com/gerrymanoim/exchange_calendars/issues/42)).

The **`late_opens`** and **`early_closes`** properties return a DatetimeIndex of those sessions that have a later open/earlier close than the prevailing regular open/close time.

In [24]:
nys.early_closes[-10:]

DatetimeIndex(['2017-11-24 00:00:00+00:00', '2018-07-03 00:00:00+00:00',
               '2018-11-23 00:00:00+00:00', '2018-12-24 00:00:00+00:00',
               '2019-07-03 00:00:00+00:00', '2019-11-29 00:00:00+00:00',
               '2019-12-24 00:00:00+00:00', '2020-11-27 00:00:00+00:00',
               '2020-12-24 00:00:00+00:00', '2021-11-26 00:00:00+00:00'],
              dtype='datetime64[ns, UTC]', freq=None)

#### Bound Trading Minutes by-sessions

The **`first_*`** and **`last_*`** methods return pd.Series with index as `sessions` and value as the corresponding trading minute (UTC) for the session. NB As explained in the [minutes tutorial](./minutes.ipynb), these minutes are not necessarily the same as the session open/close/break times.

In [25]:
nys.first_minutes

2001-10-22 00:00:00+00:00   2001-10-22 13:30:00+00:00
2001-10-23 00:00:00+00:00   2001-10-23 13:30:00+00:00
2001-10-24 00:00:00+00:00   2001-10-24 13:30:00+00:00
2001-10-25 00:00:00+00:00   2001-10-25 13:30:00+00:00
2001-10-26 00:00:00+00:00   2001-10-26 13:30:00+00:00
                                       ...           
2022-10-17 00:00:00+00:00   2022-10-17 13:30:00+00:00
2022-10-18 00:00:00+00:00   2022-10-18 13:30:00+00:00
2022-10-19 00:00:00+00:00   2022-10-19 13:30:00+00:00
2022-10-20 00:00:00+00:00   2022-10-20 13:30:00+00:00
2022-10-21 00:00:00+00:00   2022-10-21 13:30:00+00:00
Freq: C, Name: first_minutes, Length: 5289, dtype: datetime64[ns, UTC]

In [26]:
nys.last_minutes

2001-10-22 00:00:00+00:00   2001-10-22 19:59:00+00:00
2001-10-23 00:00:00+00:00   2001-10-23 19:59:00+00:00
2001-10-24 00:00:00+00:00   2001-10-24 19:59:00+00:00
2001-10-25 00:00:00+00:00   2001-10-25 19:59:00+00:00
2001-10-26 00:00:00+00:00   2001-10-26 19:59:00+00:00
                                       ...           
2022-10-17 00:00:00+00:00   2022-10-17 19:59:00+00:00
2022-10-18 00:00:00+00:00   2022-10-18 19:59:00+00:00
2022-10-19 00:00:00+00:00   2022-10-19 19:59:00+00:00
2022-10-20 00:00:00+00:00   2022-10-20 19:59:00+00:00
2022-10-21 00:00:00+00:00   2022-10-21 19:59:00+00:00
Freq: C, Name: last_minutes, Length: 5289, dtype: datetime64[ns, UTC]

In [27]:
# in terms of local times...
nys.last_minutes.dt.tz_convert(nys.tz)

2001-10-22 00:00:00+00:00   2001-10-22 15:59:00-04:00
2001-10-23 00:00:00+00:00   2001-10-23 15:59:00-04:00
2001-10-24 00:00:00+00:00   2001-10-24 15:59:00-04:00
2001-10-25 00:00:00+00:00   2001-10-25 15:59:00-04:00
2001-10-26 00:00:00+00:00   2001-10-26 15:59:00-04:00
                                       ...           
2022-10-17 00:00:00+00:00   2022-10-17 15:59:00-04:00
2022-10-18 00:00:00+00:00   2022-10-18 15:59:00-04:00
2022-10-19 00:00:00+00:00   2022-10-19 15:59:00-04:00
2022-10-20 00:00:00+00:00   2022-10-20 15:59:00-04:00
2022-10-21 00:00:00+00:00   2022-10-21 15:59:00-04:00
Freq: C, Name: last_minutes, Length: 5289, dtype: datetime64[ns, America/New_York]

In [28]:
# last pre-break minute of am subsession
hkg.last_am_minutes["2020-12-23":"2020-12-28"]

2020-12-23 00:00:00+00:00   2020-12-23 03:59:00+00:00
2020-12-24 00:00:00+00:00                         NaT
2020-12-28 00:00:00+00:00   2020-12-28 03:59:00+00:00
Freq: C, Name: last_am_minutes, dtype: datetime64[ns, UTC]

In [29]:
# first post-break minute of pm subsession
hkg.first_pm_minutes.loc["2020-12-23":"2020-12-28"]

2020-12-23 00:00:00+00:00   2020-12-23 05:00:00+00:00
2020-12-24 00:00:00+00:00                         NaT
2020-12-28 00:00:00+00:00   2020-12-28 05:00:00+00:00
Freq: C, Name: first_pm_minutes, dtype: datetime64[ns, UTC]

In [30]:
# in local time...
hkg.first_pm_minutes.loc["2020-12-23":"2020-12-28"].dt.tz_convert(hkg.tz)

2020-12-23 00:00:00+00:00   2020-12-23 13:00:00+08:00
2020-12-24 00:00:00+00:00                         NaT
2020-12-28 00:00:00+00:00   2020-12-28 13:00:00+08:00
Freq: C, Name: first_pm_minutes, dtype: datetime64[ns, Asia/Hong_Kong]

#### Nanos

Many sessions/minutes properties that return a `DatetimeIndex` have a 'nanos' equivalent that returns a numpy ndarray of integers.

Why? Internally `ExchangeCalendar` uses these nano arrays because they are faster to operate on than `DatetimeIndex`. Indeed, for some operations, working with nanos can be **much** faster.

In [31]:
hkg.sessions_nanos, hkg.minutes_nanos

(array([1003708800000000000, 1003795200000000000, 1003881600000000000, ...,
        1666137600000000000, 1666224000000000000, 1666310400000000000],
       dtype=int64),
 array([1003716000000000000, 1003716060000000000, 1003716120000000000, ...,
        1666339020000000000, 1666339080000000000, 1666339140000000000],
       dtype=int64))

In [32]:
hkg.opens_nanos, hkg.closes_nanos

(array([1003716000000000000, 1003802400000000000, 1003888800000000000, ...,
        1666143000000000000, 1666229400000000000, 1666315800000000000],
       dtype=int64),
 array([1003737600000000000, 1003824000000000000, 1003910400000000000, ...,
        1666166400000000000, 1666252800000000000, 1666339200000000000],
       dtype=int64))

In [33]:
hkg.break_starts_nanos, hkg.break_ends_nanos, 

(array([1003723200000000000, 1003809600000000000, 1003896000000000000, ...,
        1666152000000000000, 1666238400000000000, 1666324800000000000],
       dtype=int64),
 array([1003726800000000000, 1003813200000000000, 1003899600000000000, ...,
        1666155600000000000, 1666242000000000000, 1666328400000000000],
       dtype=int64))

In [34]:
hkg.first_minutes_nanos, hkg.last_minutes_nanos

(array([1003716000000000000, 1003802400000000000, 1003888800000000000, ...,
        1666143000000000000, 1666229400000000000, 1666315800000000000],
       dtype=int64),
 array([1003737540000000000, 1003823940000000000, 1003910340000000000, ...,
        1666166340000000000, 1666252740000000000, 1666339140000000000],
       dtype=int64))

In [35]:
hkg.last_am_minutes_nanos, hkg.first_pm_minutes_nanos

(array([1003723140000000000, 1003809540000000000, 1003895940000000000, ...,
        1666151940000000000, 1666238340000000000, 1666324740000000000],
       dtype=int64),
 array([1003726800000000000, 1003813200000000000, 1003899600000000000, ...,
        1666155600000000000, 1666242000000000000, 1666328400000000000],
       dtype=int64))